name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tests:

    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2','8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            php-${{ matrix.php }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, ctype, dom, fileinfo, intl, gd, json, mbstring, pdo, pdo_sqlite, openssl, sqlite, xml, zip
          coverage: none

      - name: Copy .env
        run: cp .env.testing .env

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-${{ hashFiles('package-lock.json') }}

      - name: Install NPM
        run: npm ci

      - name: Compile assets
        run: npm run production

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Execute tests
        run: php artisan test --parallel
